base/urls.py
import sys
sys.dont_write_bytecode = True

from django.urls import path
from django.contrib.auth.views import LogoutView

from base.models.nippou import Nippou
from .views import (
    Index,
    MyLoginView,
    profileform,
    ProfileListView,
    ProfileDetailView,
    NippouListView,
    NippouCreateView,
    OutputListView,
    TagOutputListView,
    OutputCreateView,
    OutputDetailView,
    StudentListView,
    PlanReplyView
)
app_name = 'base'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/edit', profileform, name='profile'),
    path('member/', ProfileListView.as_view(), name='profile-list'),
    path('member/<int:pk>/', ProfileDetailView.as_view(), name='profile-detail'),
    path('nippou/', NippouListView.as_view(), name='nippou-list'),
    path('nippou/new/', NippouCreateView.as_view(), name='nippou-create'),
    path('output/', OutputListView.as_view(), name='output-list'),
    path('output/<str:slug>', TagOutputListView.as_view(), name='tagoutput-list'),
    path('output/new/', OutputCreateView.as_view(), name='output-create'),
    path('output/detail/<int:pk>/', OutputDetailView.as_view(), name='output-detail'),
    path('teacher/', StudentListView.as_view(), name='teacher'),
    path('plan/<int:pk>', PlanReplyView.as_view(), name='plan-detail'),
]

config/urls.py
import sys
sys.dont_write_bytecode = True

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from base import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('login', views.login)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

# Create your models here.

base/models/nippou.py
import sys
sys.dont_write_bytecode = True

from django.db import models
from django.contrib.auth import get_user_model

class Nippou(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    sales = models.PositiveIntegerField(
        verbose_name='販売個数',
        default=0,
    )

    revenue = models.PositiveBigIntegerField(
        verbose_name='利益',
        default=0,
    )

    plan = models.TextField(
        verbose_name='その他',
        default='',
        null=True,
        blank=True,
    )

    date = models.DateField(
        verbose_name = '対象日'
    )

    def __str__(self):
        return str(self.date) + 'の日報'

base/models/output.py
import sys
sys.dont_write_bytecode = True

from django.db import models
from django.contrib.auth import get_user_model

class OutputTagModel(models.Model):

    tag = models.CharField(
        verbose_name = 'タグ',
        max_length = 100,
    )
    slug = models.SlugField(
        verbose_name='URL',
        unique = True,
    )

    def __str__(self):
        return self.tag


class Output(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    question = models.TextField(
        verbose_name='質問',
        null=True,
        blank=True,
    )

    description = models.TextField(
        verbose_name='内容'
    )

    created_at = models.DateTimeField(
        verbose_name = '投稿日',
        auto_now_add = True,
    )

    updated_at = models.DateTimeField(
        verbose_name = '更新日',
        auto_now = True
    )

    tags = models.ManyToManyField(
        OutputTagModel,
    )

    def __str__(self):
        return self.description[:10]

base/models/plan.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth import get_user_model
import sys
sys.dont_write_bytecode = True

STYLE = (('real', 'リアルミーティング'), ('Zoom', 'Zoom'))
ENTRY = (('real', '参加'), ('online', 'オンライン参加'), ('nonentry', '不参加'))
PARTY_ENTRY = (('entry', '参加'), ('nonentry', '不参加'))


class Plan(models.Model):
    title = models.CharField(verbose_name='タイトル', max_length=50)
    style = models.CharField(verbose_name='開催形態', max_length=50, choices=STYLE)
    zoom_link = models.URLField(verbose_name='Zoomリンク')
    open_date = models.DateField(verbose_name='開催日')
    start_time = models.TimeField(verbose_name='開始時刻')
    end_time = models.TimeField(verbose_name='終了予定時刻')
    party_time = models.TimeField(verbose_name='懇親会日時', blank=True, null=True)
    description = models.CharField(verbose_name='内容', max_length=1000)

    def __str__(self):
        return self.title

class PlanReply(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    plan = models.ForeignKey(
        Plan,
        on_delete=models.CASCADE,
    )
    entry = models.CharField(
        verbose_name='参加・不参加',
        max_length=50,
        choices=ENTRY,
        blank = True,
        null = True
    )
    party = models.CharField(
        verbose_name='懇親会',
        max_length=10,
        choices=PARTY_ENTRY,
        blank = True,
        null = True
    )
    status = models.CharField(
        verbose_name='状況',
        max_length=200,
        blank = True,
        null = True
    )
    desired = models.CharField(
        verbose_name='希望の内容',
        max_length=200,
        blank = True,
        null = True
    )
    question = models.CharField(
        verbose_name='質問・お悩み',
        max_length=500,
        blank = True,
        null = True
    )
    to_ayaka = models.CharField(
        verbose_name='梅野に聞きたいこと',
        max_length=500,
        blank = True,
        null = True
    )
    others = models.CharField(
        verbose_name='その他要望',
        max_length=500,
        blank = True,
        null = True
    )

    def __str__(self):
        return self.user.profile.name

base/models/profile.py
import sys
sys.dont_write_bytecode = True

from django.db import models
from django.contrib.auth import get_user_model

class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        unique=True,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    name = models.CharField(
        default='ウメカリメンバー',
        max_length=30,
    )

    icon = models.ImageField(
        verbose_name='アイコン',
        null=True,
        blank=True,
    )

    introduction = models.TextField(
        verbose_name='自己紹介',
        null=True,
        blank=True,
    )

    target = models.PositiveIntegerField(
        verbose_name='目標金額',
        default=0,
    )

    dream = models.ImageField(
        verbose_name='ビジョンボード',
        null=True,
        blank=True,
    )

base/forms.py
import sys
sys.dont_write_bytecode = True

from django import forms
from django.contrib.auth import get_user_model
from .models import Profile, PlanReply

class UserCreationForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ('email',)
    
    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'name',
            'icon',
            'introduction',
            'target',
            'dream',
        )

class PlanReplyForm(forms.ModelForm):
    class Meta:
        model = PlanReply
        fields = (
            'entry',
            'party',
            'status',
            'desired',
            'question',
            'to_ayaka',
            'others',
        )

base/views.py
from django.shortcuts import render

# Create your views here.

base/views/index_views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django_pandas.io import read_frame
from base.models import User, Nippou, Plan
from django.contrib.auth.mixins import LoginRequiredMixin

import pandas as pd
import datetime

# Create your views here.

class Index(LoginRequiredMixin, ListView):
    template_name = 'base/index.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_nippou =  Nippou.objects.filter(user=self.request.user).values('revenue','date').order_by('date')
        df_nippou = read_frame(user_nippou)
        df_nippou['date'] = pd.to_datetime(df_nippou['date'])
        mm = df_nippou.set_index(['date'])
        all_sum_of_revenue = mm.resample(rule='M').sum()
        sum_of_revenue_list = all_sum_of_revenue['revenue'].tolist()
        if not len(sum_of_revenue_list) == 0:
            sum_of_revenue = sum_of_revenue_list[-1]
        else:
            sum_of_revenue = 0
        context['sum_of_revenue'] = sum_of_revenue

        plans = Plan.objects.all()
        context['plans'] = plans

        return context

def login(request):
    context = {}
    return render(request, 'pages/login.html', context)

import sys
sys.dont_write_bytecode = True

base/views/nippou_views.py
import sys
sys.dont_write_bytecode = True

from django.urls import reverse
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from base.forms import ProfileForm
from base.models import User, Profile, Nippou

class NippouListView(LoginRequiredMixin, ListView):
    model = Nippou
    template_name = 'base/nippou.html'

    def get_queryset(self):
        object_list = super().get_queryset()
        return object_list.order_by('-date')

class NippouCreateView(LoginRequiredMixin, CreateView):
    model = Nippou
    fields = (
        'date',
        'sales',
        'revenue',
        'plan',
    )
    template_name = 'base/nippou_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, '日報を提出しました')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('base:index')

base/views/output_views.py
import sys
sys.dont_write_bytecode = True

from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.views.generic import ListView, CreateView, DetailView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from base.models import Output, OutputTagModel

class OutputListView(LoginRequiredMixin, ListView):
    model = Output
    template_name = 'base/output_list.html'

    def get_queryset(self):
        object_list = Output.objects.all()
        query = self.request.GET.get('query')
        if query:
            if ' ' in query or '　' in query:
                queries = query.split()
                print(queries)
                for query in queries:
                    print(query)
                    object_list = object_list.filter(
                        Q(question__icontains=query) | Q(description__icontains=query)
                    )
            else:
                object_list = object_list.filter(
                    Q(question__icontains=query) | Q(description__icontains=query)
                )
        return object_list

class TagOutputListView(LoginRequiredMixin, ListView):
    model = Output
    template_name = 'base/output_list.html'

    def get_queryset(self):
        slug = self.kwargs['slug']
        self.tag = get_object_or_404(OutputTagModel, slug=slug)
        return super().get_queryset().filter(tags=self.tag)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context

class OutputCreateView(LoginRequiredMixin, CreateView):
    model = Output
    fields = (
        'question',
        'description',
    )
    template_name = 'base/output_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        print(form)
        messages.success(self.request, 'アウトプットを作成しました')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('base:index')

class OutputDetailView(LoginRequiredMixin, DetailView):
    model = Output
    template_name = 'base/output_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['output'] = Output.objects.get(pk=self.kwargs['pk'])
        return context

base/views/plan_views.py
import sys
sys.dont_write_bytecode = True

from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.views.generic import ListView, CreateView, DetailView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from base.models import Plan, PlanReply
from ..forms import PlanReplyForm

class PlanReplyView(LoginRequiredMixin, CreateView):
    model = PlanReply
    form_class = PlanReplyForm
    template_name = 'base/plan_detail.html'

    def form_valid(self, form):
        form.instance.user = self.request.user

        reply = form.save(commit=False)

        plan_pk = self.kwargs['pk']
        plan = get_object_or_404(Plan, pk=plan_pk)

        reply.plan = plan
        reply.save()
        messages.success(self.request, '提出完了！')
        return redirect('base:plan-detail', pk=plan_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['plan'] = Plan.objects.get(pk=self.kwargs['pk'])
        return context

base/views/teacher_views.py
import sys
sys.dont_write_bytecode = True

from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.views.generic import ListView, DetailView, UpdateView
from django.utils import timezone
from django.http import JsonResponse
from django.conf import settings

from base.models import User

class StudentListView(ListView):
    model = User
    template_name = 'base/teacher.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teacher = self.request.user
        context['students'] = teacher.student.all()
        return context

base/views/usermanage_views.py
import sys
sys.dont_write_bytecode = True

import base64
import numpy as np
import os
import pandas as pd

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.views.generic import ListView, DetailView, UpdateView
from django.utils import timezone
from django.http import JsonResponse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django_pandas.io import read_frame

from base.forms import ProfileForm
from base.models import User, Profile, Nippou

class MyLoginView(LoginView):
    redirect_authenticated_user = True
    template_name = 'base/login.html'

    def form_valid(self, form):
        messages.success(self.request, 'ログイン完了！')
        return super().form_valid(form)

@login_required
def profileform(request):
    profile = request.user.profile
    icon = profile.icon
    dream = profile.dream
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            if not profile.icon:
                profile.icon = icon
            if not profile.dream:
                profile.dream = dream
            profile.save()
            print(profile.dream)
            messages.success(request, 'プロフィールが変更されました')
            return redirect('base:index')
    else:
        form = ProfileForm(request.POST, request.FILES)
    return render(request, 'base/profile_form.html', {'form': form})

class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'base/profile_list.html'

class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'base/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(pk=self.kwargs['pk'])
        context['profile'] = profile
        user_nippou =  Nippou.objects.filter(user=profile.user).values('revenue','date').order_by('date')
        df_nippou = read_frame(user_nippou)
        df_nippou['date'] = pd.to_datetime(df_nippou['date'])
        mm = df_nippou.set_index(['date'])
        all_sum_of_revenue = mm.resample(rule='M').sum()
        sum_of_revenue_list = all_sum_of_revenue['revenue'].tolist()
        if not len(sum_of_revenue_list) == 0:
            sum_of_revenue = sum_of_revenue_list[-1]
        else:
            sum_of_revenue = 0
        context['sum_of_revenue'] = sum_of_revenue
        return context

templates/base/index.html
{% extends 'base.html' %}
{% load static %}
{% load base_tags %}

{% block header %}
{% if user.is_authenticated %}
<div class="row profdiv">
    <div class="col-lg-6 main-content">
        <div class="row">
            <div class="col-lg-6 p-4">
                <div class="row">
                    <div class="col-4 col-lg-12">
                        {% if user.profile.icon %}
                        <img src="{{ user.profile.icon.url }}" alt=""  class="icon d-block mx-auto">
                        {% else %}
                        <img src="{% static 'base/images/default-icon.svg' %}" class="icon d-block mx-auto">
                        {% endif %}
                    </div>
                    <div class="col-8 col-lg-12">
                        <h3 class="pt-2">{{user.profile.name}}</h3>
                        <p class="pt-3">{{user.profile.introduction}}</p>
                        <a href="{% url 'base:profile' %}" class='a-btn'>プロフィール変更</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 p-4 align-items-center">
                <p class="text-center">ビジョンボード</p>
                {% if user.profile.dream %}
                <img src="{{ user.profile.dream.url }}" class="visionboard d-block mx-auto">
                {% else %}
                <img src="{% static 'base/images/default-icon.svg' %}" class="visionboard d-block mx-auto">
                {% endif %}
            </div>
        </div>
    </div>

    <div class="col-lg-6 sub-content">
        <div class="p-3 column">
            <p>
                今日は{% now 'Y' %}年{% now 'n' %}月{% now 'd' %}日です。
            </p>
            {% if user.is_admin %}
            <p>
                <a href="{% url 'base:teacher' %}">講師専用ページへ</a>
            </p>
            {% else %}
            <p>
                担当講師: {{ user.teacher.profile.name }}先生
            </p>
            {% endif %}
            {% if user.profile.target == 0 %}
            <p>目標金額を設定してください</p>
            {% else %}
            <p>
                目標金額: {{user.profile.target}}円
            </p>
            <p>
                本日までの合計利益: {{sum_of_revenue}}円
            </p>
            <div id="progressOfTarget"></div>
            {% endif %}
        </div>
    </div>
</div>
{% else %}
ログインしてください！
{% endif %}
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="row">
    <div class="col-6 col-lg-4 link-box">
        <a href="{% url 'base:nippou-create' %}">
            <img src="{% static 'base/images/nippou.png' %}" class="menu-icon">
        </a>
        <a href="https://ume-school.com/">
            <img src="{% static 'base/images/content.png' %}" class="menu-icon">
        </a>
    </div>
    <div class="col-6 col-lg-4 link-box">
        <a href="{% url 'base:output-create' %}">
            <img src="{% static 'base/images/output.png' %}" class="menu-icon">
        </a>
        <a href="{% url 'base:nippou-list' %}">
            <img src="{% static 'base/images/Q&A.png' %}" class="menu-icon">
        </a>
    </div>
    <div class="col-lg-4 plan-field">
        {% for plan in plans %}
            <a href="{% url 'base:plan-detail' plan.pk %}">{{plan.title}}</a>
        {% endfor %}
    </div>
</div>
{% endif %}
<script src="https://rawgit.com/kimmobrunfeldt/progressbar.js/master/dist/progressbar.js"></script>

{% if user.profile.target %}
    <script>
        var bar = new ProgressBar.Line(progressOfTarget, {
            strokeWidth: 4,
            easing: 'easeInOut',
            duration: 1400,
            color: '#FFEA82',
            trailColor: '#eee',
            trailWidth: 1,
            svgStyle: {width: '80%', height: '80%'},
            text: {
                style: {
                    // Text color.
                    // Default: same as stroke color (options.color)
                    color: 'black',
                    position: 'relative',
                    left: '0px',
                    top: '0px',
                    padding: 0,
                    margin: 'auto',
                    transform: null
                },
                autoStyleContainer: false
            },
            from: {color: '#FFEA82'},
            to: {color: '#ED6A5A'},
            step: (state, bar) => {
                bar.setText('目標達成度　' + Math.round(bar.value() * 100) + ' %');
            }
        });
        bar.animate('{%percentage sum_of_revenue user.profile.target%}');
    </script>
{% endif %}
{% endblock %}

templates/base/login.html
{% extends 'base.html' %}

{% block content %}

<h1>ログイン</h1>
<form method="post" class="p-4 m-4 bg-light border border-success roundedform-group">
    {% csrf_token %}
    <input class="form-control my-4" type="email" name="username" placeholder="Eメール">
    <input class="form-control my-4" type="password" name="password" placeholder="パスワード">
    <button type="submit" class="btn btn-success">ログイン</button>
</form>

{% endblock %}

templates/base/nippou_form.html
{% extends 'base.html' %}

{% block content %}

<h1>日報</h1>
<form method="post" class="p-4 m-4 bg-light border border-success roundedform-group">
    {% csrf_token %}
    <div class="py-2">
        <label>日付</label>
        <input class="form-control" type="date" name="date">
    </div>

    <div class="py-2">
        <label>販売個数</label>
        <div class="col-auto">
            <input type="number" class="form-control" aria-describedby="passwordHelpInline" name="sales" value=" {{ nippou.sales }} ">
        </div>
        <div class="col-auto">
            <span id="passwordHelpInline" class="form-text">
                個
            </span>
        </div>
    </div>

    <div class="py-2">
        <label>日利</label>
        <div class="col-auto">
            <input type="number" class="form-control" aria-describedby="passwordHelpInline" name="revenue" value=" {{ nippou.revenue }} ">
        </div>
        <div class="col-auto">
            <span id="passwordHelpInline" class="form-text">
                円
            </span>
        </div>
    </div>

    <div class="py-2">
        <label>その他</label>
        <textarea class="form-control" type="text" name="plan">{{ nippou.plan }}</textarea>
    </div>

    <button type="submit" class="btn btn-success mt-4">提出</button>
</form>

{% endblock %}

templates/base/nippou_list.html
{% extends 'base.html' %}

{% block content %}
<div class="switch-btn-container">
    <a href="{% url 'base:nippou-list' %}">
        <div id="nippou-btn" class="switch-btn">日報</div>
    </a>
    <a href="{% url 'base:output-list' %}">
        <div id="output-btn" class="switch-btn">アウトプット</div>
    </a>
</div>

<div class='nippou-list'>
    {% for nippou in object_list %}
    <hr>
    <table>
        <h2>{{nippou.date}}の日報</h2>
        <small>投稿者 : <a href="{% url 'base:profile-detail' nippou.user.pk %}">{{ nippou.user.profile.name }}</a></small>
        <p>販売個数 : {{nippou.sales}}個</p>
        <p>日利 : {{nippou.revenue}}円</p>
        <p>その他</p>
        <p>{{nippou.plan}}</p>
    </table>
    {% endfor %}
</div>


{% endblock %}

templates/base/output_detail.html
{% extends 'base.html' %}

{% block content %}

{{ output.question | linebreaksbr }}
<hr>
{{ output.description | linebreaksbr }}

{% endblock %}

templates/base/output_form.html
{% extends 'base.html' %}

{% block content %}

<h1>アウトプット</h1>
<form method="post" class="p-4 m-4 bg-light border border-success roundedform-group">
    {% csrf_token %}
    <div class="py-2">
        <label>質問</label>
        <textarea class="form-control" type="text" name="question">{{ output.question }}</textarea>
    </div>
    <div class="py-2">
        <label>アウトプット</label>
        <textarea class="form-control" type="text" name="description">{{ output.description }}</textarea>
    </div>

    <button type="submit" class="btn btn-success mt-4">提出</button>
</form>

{% endblock %}

templates/base/output_list.html
{% extends 'base.html' %}

{% block content %}
<div class="switch-btn-container">
    <a href="{% url 'base:nippou-list' %}">
        <div id="nippou-btn" class="switch-btn">日報</div>
    </a>
    <a href="{% url 'base:output-list' %}">
        <div id="output-btn" class="switch-btn">アウトプット</div>
    </a>
</div>

<div class="search_box col-sm-1">
    <form action="" method="get">
        <input name="query" value="{{ request.GET.query }}" type="text" placeholder="気になることを検索">
    </form>
</div>
<div class="pt-2">
    {% for tag in tags %}
        <span class="badge rounded-pill bg-light text-dark m-1">
            <a href="{%url 'base:tagoutput-list' tag.slug %}" class="text-decoration-none text-reset">
                {{ tag.tag }}
            </a>
        </span>
    {% endfor %}
</div>
<hr>
{% for output in object_list %}
<div>
    <small>
    <a href="{% url 'base:profile-detail' output.user.pk %}">
        {{ output.user.profile.name }}
    </a>
    </small>
</div>
<a href="{% url 'base:output-detail' output.pk %}">{{output.question | truncatechars:30}}</a>
<hr>
{% endfor %}

{% endblock %}

templates/base/plan_detail.html
{% extends 'base.html' %}

{% block content %}

<p>{{plan.title}}</p>
<p>{{plan.style}}</p>
<p>{{plan.zoom_link}}</p>
<p>{{plan.start_time}}</p>
<p>{{plan.end_time}}</p>
<p>{{plan.party_time}}</p>
<p>{{plan.description}}</p>
<div class="pt-3">
    <h3>出席・欠席(必ず提出してください！)</h3>
    <form method="post" class="px-4 roundedform-group" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="py-2">
            <label>参加形態</label>
            <div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="entry" id="inlineRadio1" value="real">
                    <label class="form-check-label" for="inlineRadio1">参加</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="entry" id="inlineRadio1" value="online">
                    <label class="form-check-label" for="inlineRadio1">Zoom参加</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="entry" id="inlineRadio1" value="nonentry">
                    <label class="form-check-label" for="inlineRadio1">欠席</label>
                </div>
            </div>
        </div>
        <div class="py-2">
            <label>懇親会</label>
            <div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="party" id="inlineRadio1" value="entry">
                    <label class="form-check-label" for="inlineRadio1">参加</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="party" id="inlineRadio1" value="entry">
                    <label class="form-check-label" for="inlineRadio1">欠席</label>
                </div>
            </div>
        </div>
        <div class="py-2">
        <label>状況</label>
        <input class="form-control" name="status" placeholder="例）メルカリ2ヶ月目、利益5万円（1〜22日）、初月3万円">
        </div>
        <div class="py-2">
        <label>取り上げてほしい内容</label>
        <input class="form-control" name="desired">
        </div>
        <div class="py-2">
        <label>質問・お悩み</label>
        <input class="form-control" name="question">
        </div>
        <div class="py-2">
        <label>梅野に聞きたいこと</label>
        <input class="form-control" name="to_ayaka">
        </div>
        <div class="py-2">
        <label>その他意気込みなど</label>
        <input class="form-control" name="others">
        </div>
        <button type="submit" class="btn btn-success mt-4">更新</button>
    </form>
</div>


{% endblock %}

templates/base/profile_form.html
{% extends 'base.html' %}

{% block content %}

<h1>プロフィールを変更</h1>
<form method="post" class="p-4 m-4 bg-light roundedform-group" enctype="multipart/form-data">
    {% csrf_token %}
    <label>アイコン</label>
    <input class="form-control" type="file" name="icon" id="upload_icon">
    <label>ニックネーム</label>
    <input class="form-control" type="text" name="name" value="{{ user.profile.name }}">
    <label>自己紹介</label>
    <textarea class="form-control" type="text" name="introduction">{{ user.profile.introduction }}</textarea>
    <label>目標金額</label>
    <div class="col-auto">
        <input type="number" class="form-control" name="target" value="{{ user.profile.target }}">
    </div>
    <label>ビジョンボード</label>
    <input class="form-control" type="file" name="dream" value="{{ user.profile.dream }}">
    <button type="submit" class="btn btn-success mt-4">プロフィールを変更</button>
</form>
{% endblock %}

templates/base/profile_list.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<h1>プロフィールリスト</h1>
<hr>

{% for profile in object_list %}
    <a href="{% url 'base:profile-detail' profile.pk %}">
        <div>
            {% if profile.icon %}
                <img src="{{ profile.icon.url }}" alt=""  class="list-icon">
            {% else %}
                <img src="{% static 'base/images/default-icon.svg' %}" class="list-icon">
            {% endif %}
            {{profile.name}}
        </div>
    </a>
    <hr>
{% endfor %}

{% endblock %}

templates/base/teacher.html
{% extends 'base.html' %}

{% block content %}

<h1>講師専用ページ</h1>

{% if students %}

{% for student in students %}

<a href="{% url 'base:profile-detail' student.pk %}">
    {{ student.profile.name }}
</a>

{% endfor %}

{% else %}

まだ生徒がいません．

{% endif %}

{% endblock %}