base/urls.py
import sys
sys.dont_write_bytecode = True

from django.urls import path
from django.contrib.auth.views import LogoutView

from base.models.nippou import Nippou
from .views import (
    Index,
    MyLoginView,
    profileform,
    ProfileListView,
    ProfileDetailView,
    NippouListView,
    NippouCreateView,
    OutputListView,
    TagOutputListView,
    OutputCreateView,
    OutputDetailView,
    StudentListView,
    PlanReplyView
)
app_name = 'base'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/edit', profileform, name='profile'),
    path('member/', ProfileListView.as_view(), name='profile-list'),
    path('member/<int:pk>/', ProfileDetailView.as_view(), name='profile-detail'),
    path('nippou/', NippouListView.as_view(), name='nippou-list'),
    path('nippou/new/', NippouCreateView.as_view(), name='nippou-create'),
    path('output/', OutputListView.as_view(), name='output-list'),
    path('output/<str:slug>', TagOutputListView.as_view(), name='tagoutput-list'),
    path('output/new/', OutputCreateView.as_view(), name='output-create'),
    path('output/detail/<int:pk>/', OutputDetailView.as_view(), name='output-detail'),
    path('teacher/', StudentListView.as_view(), name='teacher'),
    path('plan/<int:pk>', PlanReplyView.as_view(), name='plan-detail'),
]

config/urls.py
import sys
sys.dont_write_bytecode = True

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from base import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('login', views.login)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/messages.html
{% for msg in messages %}
<nav class="{{ msg.tags }}">
    <div class="container">
        {{ msg }}
    </div>
</nav>
{% endfor %}

templates/snippets/navigation.html
{% load static %}

<div class="container-fluid header-logo">
    <div class="row">
        <div class="col-lg-4 col-8">
            <a class="navbar-brand" href="{% url 'base:index' %}">
                <img src="{% static 'base/images/logo_umecari.png' %}" class="top-logo">
            </a>
        </div>
        <div class="col-4 col-lg-8 loginout">
            {% if user.is_authenticated %}
            <a href="{% url 'base:logout' %}">ログアウト</a>
            {% else %}
            <a href="{% url 'base:login' %}">ログイン</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="container-fluid menu">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-4 col-lg-2">
            <a href="{% url 'base:index' %}">
                <div class="menu-btn">
                    ホーム
                </div>
            </a>
        </div>
        <div class="col-4 col-lg-2">
            <a class="" href="{% url 'base:profile-list' %}">
                <div class="menu-btn">
                    ウメカリメンバー
                </div>
            </a>
        </div>
        <div class="col-4 col-lg-2">
            <a class="" href="{% url 'base:nippou-list' %}">
            <div class="menu-btn">
                みんなの投稿
            </div>
            </a>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>